travis:
  secure:
    BINSTAR_TOKEN: cge2m3+EYDXsA9+py5BNQ2fO5rRpCkjgyBMJohaZf3wFy8RZwznZpYWerqImRZQDqZ07lzQL6Mxc3Au+KYuT9HqJ0X/AFyCQk4Kz7aMZSKtIA7/fsFoDRqv0P5Fpo2SXG+uWoumean4fNJcYYm3f2ZHbI0Sv+4VhhQGn1GCqGqpm/U0q9gYs84cTJKMWAd2JfqzxAUQOdZ7Z7FUVx5W9rMNgrP07yLlNQYYx8g06KbAMOA9utFXm7OrF4sWHSCIMcY1+636hlFz1IQNzhwvmYmbKWekXfwJ1+5RHNmBHHd0IM7tIedgVIaSr73kqvnP9YsCI7vabKQN/a4DU5oxFwni6mMzusRgWdKFtzWJ70/dXaUwguyIdGXZEdLuWry+yxAB5vRF34i/WJKUSQv3+RDb3v3IxVd8c6YOfoWHQTOu3YOtRQLo40Etxp30ygkyiJPUGa0MJLBlwRJ/wLPCvyX6gglqdQGKmC8KHSSLXC0Fb8wgHgkrxMb3keemWqBchLNjcAaWtpwV4mfBdRbyvfCqI1G4cEfOXdzrRdaJbZzJawrS+zp22OzviOH+DquHQpPIoDq76UzQH7OiQdeslhCB5Amw9VNgdZUD2nF7rYvP8RKRfXIXvq9L1dV/rJic73y2tOr7nvWidix937pFw4HzJ5Sp1IEtcH++djZysBfE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
